# DOCS https://microsoft.github.io/pyright/#/configuration
# https://docs.basedpyright.com/v1.21.0/configuration/config-files/
[tool.basedpyright] # also used by basedpyright
venvPath = "."
venv = ".venv"
typeCheckingMode = "recommended" # https://docs.basedpyright.com/v1.21.0/configuration/config-files/#diagnostic-settings-defaults

# diagnostics
reportUnusedVariable = "information"

[tool.python.analysis]
diagnosticMode = "workspace"

#───────────────────────────────────────────────────────────────────────────────

# DOCS https://beta.ruff.rs/docs/rules/
[tool.ruff]
line-length = 100
exclude = [".venv", "typings/*.pyi"]
select = ["ALL"]
ignore = [
	# comments & debugging
	"T201",   # print statements
	"T100",   # "breakpoint()"
	"ERA001", # commented out code
	"TD",     # allow TODO
	"FIX002", # complain about TODO in general
	"FIX004", # complain about HACK

	# already auto-fixed by formatter
	"W",      # pycodestyle warnings
	"COM812", # trailing comma in call

	# duplicaton with `pyright`
	"F841",   # unused var
	"F401",   # unused import
	"ARG001", # unused arg
	"F821",   # undefined variable

	# misc
	"S311",   # requires cryptographically secure random number generators
	"RET504", # unnecessary assign for return (makes stuff less verbose)
]

[tool.ruff.pydocstyle]
convention = "google" # "google"|"numpy"|"pep257"

#───────────────────────────────────────────────────────────────────────────────
